theme: slate

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: compressed

title: Your Site Title
description: Your site description
url: https://your-site-url.com
baseurl: /your-site-baseurl

# Optional customizations for header and footer
header_links:
  - title: Home
    url: /
  - title: About
    url: /about
footer_links:
  - title: Privacy Policy
    url: /privacy
  - title: Contact Us
    url: /contact
